title:            Vinyl Dojo
tagline:          Nerdy Music Blog.
description:      Random Nerdy Music Blog.
canonical:        rafascensao.github.io

# Owner/author information
owner:
  name:           Pedro Ascensao
  avatar:         avatar.png
  bio:            "Music & Water Sommelier"
  email:          rafascen@gmail.com
  github:         rafaascensao
  instagram:      barriganegra
  location:       "Lisbon, Portugal"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: Reviews
    url: /reviews
  - title: Playlists
    url: /playlists 
  - title: About
    url: /about
  - title: Github
    url: https://github.com/rafaascensao/rafaascensao.github.io
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Lisbon
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
